# Generated by Django 4.2.7 on 2023-12-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiberarts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crochet',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='fiber',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='knitting',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='spinning',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='yarn',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
