# Generated by Django 4.2.7 on 2023-11-28 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('photo_url', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completetion_status', models.BooleanField(default=False)),
                ('pattern_name', models.CharField(blank=True, null=True)),
                ('pattern_designer', models.CharField(blank=True, null=True)),
                ('tools_used', models.TextField()),
                ('yarn', models.CharField(blank=True, null=True)),
                ('fiber', models.CharField(blank=True, null=True)),
                ('plys', models.CharField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
