# Generated by Django 4.2.7 on 2023-11-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiberart', '0002_project_project_type_alter_project_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stash',
            name='amount',
        ),
        migrations.AddField(
            model_name='stash',
            name='yardage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
